"""Port do client da API legada (consumida pelo MCP server via REST)."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


class LegacyValidationError(Exception):
    """Erro de validacao do backend legado (HTTP 422)."""


@runtime_checkable
class LegacyApiClient(Protocol):
    def find_customer(self, phone: str) -> dict[str, Any] | None: ...
    def list_contracts(self, titular_id: str) -> list[dict[str, Any]]: ...
    def list_invoices(self, uc_id: str) -> list[dict[str, Any]]: ...
    def invoice_pdf(self, fatura_id: str, presigned: bool = False) -> dict[str, Any]: ...
    def send_invoice(self, fatura_id: str) -> dict[str, Any]: ...
    def get_outage(self, bairro: str) -> dict[str, Any]: ...
    def create_ticket(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def get_ticket(self, protocolo: str) -> dict[str, Any] | None: ...
    def create_handoff(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def search_kb(self, query: str) -> list[dict[str, Any]]: ...
    def get_conversation_memory(
        self, chat: str, limit: int = 10
    ) -> list[dict[str, Any]]: ...
    def get_chat_messages(
        self, phone: str, limit: int = 10
    ) -> list[dict[str, Any]]: ...
